[package]
name = "struct_munger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
toml = "0.8.12"
toml_edit = "0.22.9"
serde = "1.0.197"
ariadne = "0.4.0"
log = "0.4.21"
env_logger = "0.11.3"
